### ISSUE TITLE
mf.transform(x=test) gives error

### ISSUE THREAD

**Issue by kawseribn** [yuenshingyan/MissForest#26]
```clf = RandomForestClassifier(n_jobs=-1)
rgr = RandomForestRegressor(n_jobs=-1)

mf = MissForest(clf, rgr)
mf.fit(X_missing)

X_imputed = mf.transform(X_missing)

x_test_imputed = mf.transform(x=test) #this generates the error
```
<img width="696" alt="image" src="https://github.com/yuenshingyan/MissForest/assets/46264704/6a7e789f-0e6f-4981-a6c5-186f56b5f80c">

**Comment by yuenshingyan** [comment]
Is that possible to give me the dataset and full code, since it is hard to re-create the bug without them ?

**Comment by chris-membrey** [comment]
the issue comes from training using .fit_transform and then attempting to transform on new data. It seems the trained object will expect a new dataset at least the size of the trained dataset, but in reality, you may want to just transform just one row.

**Comment by yuenshingyan** [comment]
I have fixed the bug and also added some simple tests. https://pypi.org/project/MissForest/
