### ISSUE TITLE
Not Handling Categorical Variables unseen by training data

### ISSUE THREAD

**Issue by chris-membrey** [yuenshingyan/MissForest#28]
<img width="906" alt="Screenshot 2023-12-28 at 10 04 47" src="https://github.com/yuenshingyan/MissForest/assets/135331031/fcc98d09-52b3-4c20-821f-4d852c71fecf">

I get this error when transforming on my dataset that contains a postal districts column (UK). I think the error comes from categorical variables that have not been seen in the training set. is there a mechanism in place for handling this? Thanks.

**Comment by yuenshingyan** [comment]
@chris-membrey Hi, I have just enhanced the 'transform' method so that it will now deal with unseen categories. 
pip install MissForest==2.4.2

**Comment by chris-membrey** [comment]
Thank you!
