### ISSUE TITLE
Learning classifiers and regressors on rows with no missings only

### ISSUE THREAD

**Issue by Vlad382** [yuenshingyan/MissForest#53]
Dear yuenshingyan,

First of all, thanks for your package!

While using the Python version of missForest, we noticed that your implementation is a bit different from the one described in the source paper and in the R code. Namely, your classifiers and regressors train only on the data that have no missing rows at all ([line 511-512](https://github.com/yuenshingyan/MissForest/blob/main/src/missforest/missforest.py#L511-L512)). The original algorithm trains on the full set of other features. This can be done because of the initial guess for the missing values. Otherwise, the initial guess is redundant and not used.

Vlad

**Comment by yuenshingyan** [comment]
Thank you @Vlad382.

I believe that you're right. I have just update the algorithm to make it trains on the full dataset.

https://pypi.org/project/MissForest/3.1.1/ is published.
