### ISSUE TITLE
Fit should store fitted estimators, Transform should use previously fitted estimators

### ISSUE THREAD

**Issue by adamvvu** [yuenshingyan/MissForest#76]
Hi,

Thanks for sharing this package!

Briefly skimming over the Miss Forest paper by Stekhoven and Buhlmann (2012), it seems that the algorithm is essentially just imputing missing values by predictions with random forests.

Unless I'm missing something that prohibits this, it would be helpful if the actual fitting of the estimators is moved into `.fit()` and then stored. Currently `.fit` only does some validation of data structures and initialization, while `.transform` is doing the actual fitting. Ideally, or at least consistent with sklearn syntax, `.transform` should use the pre-fitted estimators and be very fast. 

You could probably just combine `.fit` and `.transform` into a single `.fit`, and save the estimators into a dictionary that indexes columns. Then create a new `.transform` method that uses the previously fit estimators.

An example use case in practice might be:
```
# Training
X = # Large DataFrame for training
mf = MissForest()
mf.fit(X)   # Fit the estimators on the training dataset

# After deploying the model
X_new = # Small DataFrame, for example new live data that comes in
mf.transform(X_new)   # Use the previously fit estimators to impute, should be very fast
```

**Comment by yuenshingyan** [comment]
This is actually what I thought when I started this project. I will try to implement this and compare it with the old approach.
