### ISSUE TITLE
Previous Versions Removed, Only One Version Available

### ISSUE THREAD

**Issue by gnaneshwarbandari** [yuenshingyan/MissForest#89]
**Description**
It seems that previous versions of the package are no longer available, and the page now only points to the latest version (4.2.2). The release history is showing a single version, released about 5 hours ago.

**Steps to Reproduce**

1. Go to the package release page.
2. Check the "Release history" section.
3. Observe that only one version (4.2.2) is displayed.

**Expected Behavior**
The page should list all previous versions of the package for users to download or reference as needed.

**Actual Behavior**
Only the latest version (4.2.2) is displayed, and all previous versions appear to have been removed.

**Impact**

- Users relying on older versions cannot access or install them.
- Dependency issues might arise for projects that are tied to earlier versions.

**Screenshot**
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/fac1a9ed-b5c7-4060-86a8-186ea4e40fef" />

**Comment by yuenshingyan** [comment]
I intentionally deleted previous versions, since I think users should encode categorical data themselves.
